
function StundetPlanMessage() {

    return (
   <div
        className="whitespace-nowrap animate-marquee
                            text-[13px] font-medium tracking-wide
                            text-slate-700 dark:text-slate-300 px-4"
      >
        ℹ️ This plan is generated by AI using your details and today’s mess menu. It gives a general idea and may not be 100% exact.
      </div>
  )
  
}

export default StundetPlanMessage