import {
  Utensils,
  Moon,
  Activity,
  Sparkles,
  Calendar,
  Target,
  Route,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
// import StundetPlanMessage from "../StudentMessage/StundetPlanMessage";

export default function StudentPlanResult({ data, source }: any) {
   
    if(!data) return;

  return (
       
        <div className="w-full max-w-4xl mx-auto space-y-6 text-slate-200">

    <div
        className="text-slate-700 dark:text-slate-300 px-4"
      >
        ℹ️ This plan is generated by AI using your details and today’s mess menu. It gives a general idea and may not be 100% exact.
      </div>
      
      {/* ================= Summary ================= */}
      {/* <Card className="rounded-2xl bg-white/5 border border-white/10">
        <CardContent className="p-6">
          <h3 className="font-semibold text-lg mb-2 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-yellow-400" />
            Summary
          </h3>
          <p className="text-slate-300">{data.summary}</p>
        </CardContent>
      </Card> */}

      <Card
        className="
  relative overflow-hidden rounded-3xl
  bg-gradient-to-br from-yellow-500/20 via-orange-500/10 to-blue-900/20
  border border-white/10 shadow-2xl
"
      >
        {/* glow */}
        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent animate-pulse" />
        <CardContent className="relative p-8 space-y-3">
          <h3 className="text-xl font-bold flex items-center gap-2 text-black dark:text-white">
            <Sparkles className="w-5 h-5 text-yellow-400" />
            Today’s Smart Plan
          </h3>

          <p className="text-black dark:text-slate-200 text-base leading-relaxed">
            {data.summary}
          </p>
        </CardContent>
      </Card>

      {/* ================= Header ================= */}
      {/* <Card className="rounded-2xl bg-white/5 backdrop-blur border border-white/10 shadow-xl">
        <CardContent className="p-6 flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold flex items-center gap-2">
              <Calendar className="w-5 h-5 text-sky-400" />
              {data.day} Plan
            </h2>
            <p className="text-slate-400 flex items-center gap-2 mt-1 capitalize">
              <Target className="w-4 h-4 text-emerald-400" />
              Goal: {data.goal.replace("_", " ")}
            </p>
          </div>

          <Badge
            className={`${
              source === "cache"
                ? "bg-emerald-500/20 text-emerald-400"
                : "bg-sky-500/20 text-sky-400"
            }`}
          >
            {source === "cache" ? "Saved Plan" : "AI Generated"}
          </Badge>
        </CardContent>
      </Card> */}

      {/* ================= Meals ================= */}
      {/* <Card className="rounded-2xl bg-white/5 border border-white/10">
        <CardContent className="p-6 space-y-4">
          <div className="flex items-start gap-3">
            <Utensils className="w-5 h-5 text-orange-400 mt-1" />
            <p className="text-slate-300">
              <span className="font-semibold text-slate-100">Lunch:</span>{" "}
              {data.lunch.join(", ")}
            </p>
          </div>

          <div className="flex items-start gap-3">
            <Moon className="w-5 h-5 text-indigo-400 mt-1" />
            <p className="text-slate-300">
              <span className="font-semibold text-slate-100">Dinner:</span>{" "}
              {data.dinner.join(", ")}
            </p>
          </div>
        </CardContent>
      </Card> */}

      <Card
        className="
    relative overflow-hidden
    rounded-3xl
    bg-gradient-to-br from-sky-500/15 via-indigo-500/10 to-emerald-500/15
    border border-white/10
    shadow-2xl
  "
      >
        {/* subtle glow */}
        <div className="absolute inset-0 bg-white/5 pointer-events-none" />

        <CardContent className="relative p-8 space-y-6">
          {/* ================= Header ================= */}
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-3xl font-bold flex items-center gap-2 dark:text-white">
                <Calendar className="w-6 h-6 text-sky-400" />
                {data.day} Plan
              </h2>
              <p className="dark:text-slate-300 flex items-center gap-2 mt-1 capitalize">
                <Target className="w-4 h-4 text-emerald-400" />
                Goal: {data.goal.replace("_", " ")}
              </p>
            </div>

            <Badge
              className={`px-4 py-1.5 text-sm ${
                source === "cache"
                  ? "bg-emerald-500/20 text-emerald-400"
                  : "bg-sky-500/20 text-sky-400"
              }`}
            >
              {source === "cache" ? "Saved Plan" : "AI Generated"}
            </Badge>
          </div>

          {/* ================= Divider ================= */}
          <div className="h-px bg-white/10" />

          {/* ================= Meal Overview ================= */}
          <div className="space-y-4">
            <div className="flex items-start gap-3">
              <Utensils className="w-5 h-5 text-orange-400 mt-1" />
              <p className="dark:text-slate-200 text-base">
                <span className="font-semibold dark:text-slate-100">Lunch:</span>{" "}
                {data.lunch.join(", ")}
              </p>
            </div>

            <div className="flex items-start gap-3">
              <Moon className="w-5 h-5 text-indigo-400 mt-1" />
              <p className="dark:text-slate-200 text-base">
                <span className="font-semibold dark:text-slate-100">Dinner:</span>{" "}
                {data.dinner.join(", ")}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* ================= Meal Suggestions ================= */}
      {/* <Card className="rounded-2xl bg-white/5 border border-white/10">
        <CardContent className="p-6 space-y-4">
          <h3 className="font-semibold text-lg">🍽️ Meal Suggestions</h3>
          <p className="text-slate-300">
            <span className="font-medium text-slate-100">Lunch:</span>{" "}
            {data.meal_suggestion.lunch}
          </p>
          <p className="text-slate-300">
            <span className="font-medium text-slate-100">Dinner:</span>{" "}
            {data.meal_suggestion.dinner}
          </p>
        </CardContent>
      </Card> */}
      <Card
        className="
    relative overflow-hidden
    rounded-3xl
    bg-gradient-to-br from-emerald-500/15 via-sky-500/10 to-indigo-500/15
    border border-white/10
    shadow-xl
  "
      >
        {/* subtle glow */}
        <div className="absolute inset-0 bg-white/5 pointer-events-none" />

        <CardContent className="relative p-8 space-y-6">
          {/* TITLE */}
          <h3 className="text-2xl font-bold dark:text-white flex items-center gap-2">
            <Route className="w-6 h-6 text-orange-600" />
            How to Eat Today
          </h3>

          {/* LUNCH */}
          <div className="space-y-2">
            <h4 className="text-lg font-semibold dark:text-emerald-300">Lunch</h4>
            <p
              className="
        text-base
        dark:text-slate-200
        bg-white/5
        border border-white/10
        rounded-xl
        px-4 py-3
      "
            >
              {data.meal_suggestion.lunch}
            </p>
          </div>

          {/* DINNER */}
          <div className="space-y-2">
            <h4 className="text-lg font-semibold dark:text-sky-300">Dinner</h4>
            <p
              className="
        text-base
        dark:text-slate-200
        bg-white/5
        border border-white/10
        rounded-xl
        px-4 py-3
      "
            >
              {data.meal_suggestion.dinner}
            </p>
          </div>
        </CardContent>
      </Card>

      {/* ================= Workout ================= */}
      {/* <Card className="rounded-2xl bg-white/5 border border-white/10">
        <CardContent className="p-6">
          <h3 className="font-semibold text-lg mb-2 flex items-center gap-2">
            <Activity className="w-5 h-5 text-pink-400" />
            Workout
          </h3>
          <p className="text-slate-300">{data.workout_suggestion}</p>
        </CardContent>
      </Card> */}

      <Card
        className="
    relative rounded-3xl
    bg-gradient-to-br from-pink-500/15 via-rose-500/10 to-orange-500/15
    border border-white/10
    shadow-lg
  "
      >
        <CardContent className="p-8 space-y-4">
          {/* Title */}
          <h3 className="text-2xl font-bold flex items-center gap-3 dark:text-white">
            <Activity className="w-6 h-6 text-pink-400" />
            Today’s Workout
          </h3>

          {/* Workout text */}
          <p
            className="
      text-base dark:text-slate-200
      bg-white/5 border border-white/10
      rounded-xl px-4 py-3
      leading-relaxed
    "
          >
            {data.workout_suggestion}
          </p>
        </CardContent>
      </Card>

      {/* ================= Tips ================= */}
      {/* <Card className="rounded-2xl bg-white/5 border border-white/10">
        <CardContent className="p-6">
          <h3 className="font-semibold text-lg mb-2">💡 Extra Tips</h3>
          <ul className="list-disc pl-5 space-y-1 text-slate-300">
            {data.extra_tips.map((tip: any, idx: any) => (
              <li key={idx}>{tip}</li>
            ))}
          </ul>
        </CardContent>
      </Card> */}

      <Card
        className="
    relative rounded-3xl
    bg-gradient-to-br from-yellow-500/10 via-amber-500/10 to-emerald-500/10
    border border-white/10
    shadow-lg
  "
      >
        <CardContent className="p-8 space-y-4">
          {/* Title */}
          <h3 className="text-2xl font-bold dark:text-white flex items-center gap-2">
            💡 Extra Tips for Today
          </h3>

          {/* Tips list */}
          <ul className="space-y-3">
            {data.extra_tips.map((tip: any, idx: any) => (
              <li
                key={idx}
                className="
            flex items-start gap-3
            dark:text-slate-200 text-base
            bg-white/5 border border-white/10
            rounded-xl px-4 py-3
          "
              >
                <span className="text-emerald-400 mt-1">✔</span>
                <span>{tip}</span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </div>
       
  );
}
